[tasks."echo"]
script = '''
echo "Hello World"
'''

[tasks."build:ui"]
script = '''
bun i
bun run build
'''

[tasks."credx-clean:build"]
script = '''
cd crates/credx-clean
cargo test
wasm-pack test --firefox --no-default-features --features wasm
'''

[tasks."near:echo"]
env = {"CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS" = "near"}
run_task = {name = "echo", fork = true}

[tasks."test:credx"]
script = '''
wasm-pack test --firefox --no-default-features --features wasm
'''
[tasks."icp:build"]
script = '''
cd icp/src/icpx_backend
dfx build
'''

[tasks."icp:call"]
script = '''
cd icp/src/icpx_backend
cargo make call:echo_base58
'''

[tasks."near:build"]
script = '''
cd near
cargo build --target wasm32-unknown-unknown
'''

[tasks."solana:build"]
script = '''
cd solana/programs/counter
anchor build -p counter
'''

[tasks."install:sui-client-gen"]
script = '''
cargo install --locked --git https://github.com/kunalabs-io/sui-client-gen.git
'''
