[tasks.pwd]
script = '''
pwd
'''

[tasks.setup]
script = '''
sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
rustup target add wasm32-unknown-unknown
'''

[tasks.'start:local']
script = '''
dfx start --background --clean
'''

[tasks.'stop:local']
script = '''
dfx stop
'''

[tasks."build:wasm"]
script = '''
dfx build
'''

[tasks.deploy]
script = '''
dfx deploy
'''

[tasks."call:counter"]
script = '''
dfx canister call icpx_backend get
dfx canister call icpx_backend set 1
dfx canister call icpx_backend get
dfx canister call icpx_backend increment
dfx canister call icpx_backend get
'''

[tasks."call:echo"]
script = '''
dfx canister call icpx_backend echo '(
  "Hello World",
)'
'''

[tasks."call:echo"]
script = '''
dfx canister call simple_oracle encrypted_symmetric_key_for_caller '(
  "Hello World",
)'
'''
