
[tasks."install:solana"]
# sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
script = '''
sh -c "$(curl -sSfL https://release.solana.com/v1.17.5/install)"
cargo install --git https://github.com/project-serum/anchor anchor-cli --locked
'''

[tasks."update::solana"]
script = '''
solana-install update
cargo install --git https://github.com/project-serum/anchor anchor-cli --locked
'''

[tasks."start:local"]
script = '''
solana-test-validator
'''

[tasks."build:counter"]
script = '''
anchor build -p counter
'''
