

[tasks."build:std"]
script = '''
cargo build
'''

[tasks."build:wasm"]
script = '''
cargo build --target wasm32-unknown-unknown --no-default-features --features wasm
'''

[tasks."test:wasm"]
script = '''
wasm-pack test --firefox --no-default-features --features wasm
'''
