[tasks."install:dev"]
script = '''
curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
'''

[tasks."build:js"]
script = '''
wasm-pack build --target nodejs
'''

[tasks."release:js"]
script = '''
wasm-pack build --target nodejs --release
'''

[tasks."publish:js"]
dependencies = ["release:js"]
script = '''
wasm-pack publish
'''
