[tasks.setup]
script = '''
sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
rustup target add wasm32-unknown-unknown
'''

[tasks.deploy]
script = '''
dfx deploy
'''

[tasks."call:counter"]
script = '''
dfx canister call icpx_backend get
dfx canister call icpx_backend set 1
dfx canister call icpx_backend get
dfx canister call icpx_backend increment
dfx canister call icpx_backend get
'''

[tasks."call:pg"]
script = '''
dfx canister call icpx_backend pg
'''
