[package]
name = "muzin"
version = "0.0.1"

[dependencies]
Sion = {local = "../sion"}
Sui = {git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet"}

[addresses]
muzin = "0x0"
