[workspace]
[package]
authors = [
  "Hyperledger AnonCreds Contributors <anoncreds@lists.hyperledger.org>",
]
categories = ["authentication", "cryptography"]
description = "Verifiable credential issuance and presentation for Hyperledger AnonCreds (https://www.hyperledger.org/projects), which provides a foundation for self-sovereign identity."
edition = "2021"
keywords = ["hyperledger", "ssi", "verifiable", "credentials"]
license = "Apache-2.0"
name = "anoncreds"
readme = "../README.md"
repository = "https://github.com/hyperledger/anoncreds-rs/"
rust-version = "1.58"
version = "0.2.0-dev.2"

[lib]
crate-type = ["staticlib", "rlib", "cdylib"]
name = "anoncreds"
path = "src/lib.rs"

[features]
default = ["ffi", "logger", "zeroize"]
ffi = ["dep:ffi-support"]
logger = ["dep:env_logger"]
vendored = ["anoncreds-clsignatures/openssl_vendored"]
wasm = ["wasm-bindgen", "wasm-logger", "console_error_panic_hook", "serde-wasm-bindgen", "getrandom/js"]
zeroize = ["dep:zeroize"]

[dependencies]
anoncreds-clsignatures = {version = "0.2.2", default-features = false, features = ["serde"]}
bitvec = {version = "1.0.1", features = ["serde"]}
bs58 = "0.4.0"
console_error_panic_hook = {version = "0.1.7", optional = true}
env_logger = {version = "0.9.3", optional = true}
ffi-support = {version = "0.4.0", optional = true}
getrandom = {version = "0.2", optional = true}
log = "0.4.17"
once_cell = "1.17.1"
rand = "0.8.5"
regex = "1.7.1"
serde = {version = "1.0.155", features = ["derive"]}
serde-wasm-bindgen = {version = "0.4", optional = true}
serde_json = {version = "1.0.94", features = ["raw_value"]}
sha2 = "0.10.6"
thiserror = "1.0.39"
wasm-bindgen = {version = "0.2.84", optional = true}
wasm-logger = {version = "0.2.0", optional = true}
zeroize = {version = "1.3", optional = true, features = ["zeroize_derive"]}

[profile.release]
codegen-units = 1
lto = true
