[package]
name = "bbs-icp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bbs = "0.4.1"
bbs_plus = "0.16.0"
hex = "0.4.3"
