# fly.toml app configuration file generated for sion-prover on 2023-12-07T23:36:34+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sion-prover"
primary_region = "nrt"

[build]

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8080
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
