#
# SPDX-License-Identifier: CC-BY-4.0
#

repository:
  name: anoncreds-v2-rs
  description: anoncreds-v2-rs
  homepage: https://wiki.hyperledger.org/display/anoncreds
  default_branch: main
  has_downloads: false
  has_issues: true
  has_projects: true
  has_wiki: true
  archived: false
  private: false
  allow_squash_merge: false
  allow_merge_commit: false
  allow_rebase_merge: true
