[package]
description = "Created with Anchor"
edition = "2021"
name = "counter"
resolver = "2"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "lib"]
name = "counter"

[features]
cpi = ["no-entrypoint"]
default = []
no-entrypoint = []
no-idl = []
no-log-ix-name = []

[dependencies]
anchor-lang = "0.29.0"
ark-groth16 = { version = "0.4.0", default-features = false }
# bulletproofs_amcl = {git = "https://github.com/hyperledger-archives/ursa.git", rev = "c29fdaa96bbe9ce3ea2beb4d5fbe98ed7c96f867", package = "bulletproofs_amcl"}
# getrandom = {version = "0.2.9", features = ["custom"]}

# Success to build
# bbs_plus = {version = "*", features = ["std"], default-features = false}

# anchor-lang = {path = "../../../crates/anchor/lang"}
# credx = {path = "../../../crates/credx", default-features = false, features = ["wasm"]}
# credx = {path = "../../../crates/credx"}
# zeroize = "1.6.0"
